---
# Variables specific to web servers

apache_listen_ports:
  - 80
  - 8080

apache_document_root: /srv/web
apache_modules:
  - ssl
  - rewrite
  - proxy
  - proxy_http

php_packages:
  - php
  - php-mysqlnd
  - php-fpm
  - php-json
  - php-gd
  - php-mbstring
  - php-xml

nfs_client_enabled: yes
wordpress_enabled: no  # Override in host_vars/web01.yml
