[lb]
LB01 ansible_host=192.168.56.11

[webservers]
WEB01 ansible_host=192.168.56.21
WEB02 ansible_host=192.168.56.22

[storage]
Storage01 ansible_host=192.168.56.30

[database]
DB-central01 ansible_host=192.168.56.40

[all:vars]
ansible_python_interpreter=/usr/bin/python3
domain_name=example.com
db_password=SecurePassword123!
nfs_server=192.168.56.30
db_host=192.168.56.40
