[lb]
lb01 ansible_host=192.168.56.11

[webservers]
web01 ansible_host=192.168.56.21
web02 ansible_host=192.168.56.22

[storage]
storage01 ansible_host=192.168.56.30

[database]
db-central01 ansible_host=192.168.56.40

[all:vars]
ansible_python_interpreter=/usr/bin/python3
domain_name=example.com
